# Configuration Settings for ZED-F9P device

debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyGPSR
frame_id: gps_rear
uart1:
  baudrate: 460800

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true

fix_mode: 2d
dynamic_model: automotive 
